### ISSUE TITLE
"Natural row height" does not work

### ISSUE THREAD

**Issue by marquetd** [inovua/reactdatagrid#12]
- what edition are you using - community but i can reproduce it on entreprise
- version 4.0.15

Relevant code or config
https://reactdatagrid.io/docs/api-reference#props-minRowHeight

What you did:
Try to use natural row height rendering with rowHeight=null and minRowHeight

What happened:
The big cell doesn't render as expected
![image](https://user-images.githubusercontent.com/1841731/101977647-38ebea00-3c4f-11eb-80e8-0a00207491ff.png)

Reproduction repository:
Documentation example : https://reactdatagrid.io/docs/api-reference#props-minRowHeight

Problem description:

The natural row height doesn't not work
![image](https://user-images.githubusercontent.com/1841731/101977697-b0ba1480-3c4f-11eb-91a1-07061bbb6180.png)

With virtualized={false} the table does not render
![image](https://user-images.githubusercontent.com/1841731/101977710-de9f5900-3c4f-11eb-8d90-e351edf31530.png)

**Comment by idoshr** [comment]
I also tried and it doesn't work.
Hope someone here can help with the Dynamic row height

**Comment by inovua-admin** [comment]
Thanks for reporting, we're working on a fix for this.

**Comment by inovua-admin** [comment]
Thanks for the patience on this - we've had a few other issues cropping up and also this is high complexity, but we're on it.

**Comment by marquetd** [comment]
Thanks for replying.

Take your time to fixed it as well as possible !

**Comment by inovua-admin** [comment]
We've come up with a canary version as this is still in a feedback stage - please test it on version `4.0.26-canary.2`

Feedback is welcomed 🎉

For this to work properly, make sure you specify both `rowHeight=null` and `minRowHeight={number}` (the minRowHeight should be, as named, the minimum height of rows - our implementation scenario is that most rows will have this height, with some of the rows having a natural height) - see https://codesandbox.io/s/crazy-jang-iqg2b?file=/src/App.js for a demo

Important note: obviously, the performance of grids with natural-height rows will be far from the perf of grids with fixed sized rows. Also, column virtualization is no longer possible, since the grid can't know which cell/column in a row gives size of the row - so performance will degrade as you add more columns.

**Comment by marquetd** [comment]
Hi,

it's working ! Thanks ! 👍

**Comment by idoshr** [comment]
Work good for me also!!
👍👍👍👍👍
tnx
