### ISSUE TITLE
allowUnsort={false} does not work on multisort

### ISSUE THREAD

**Issue by tpae** [inovua/reactdatagrid#163]
- what edition are you using - community / enterprise
- `@inovua/reactdatagrid-enterprise` - 4.1.20

Relevant code or config

```javascript
<ReactDataGrid
  licenseKey={REACT_DATA_GRID_LICENSE_KEY}
  allowUnsort={false}
  {...props}
/>
```

What you did:
Setting `allowUnsort` to `false` should disable unsorting, but in multisport, it actually has unsorting even when `allowUnsort` is set to false.

Suggested solution:

Allow `allowUnsort` to work with multi sort configuration

**Comment by inovua-admin** [comment]
For multi sort feature, we need unsort state on the columns. Because, if I sort the first column (the first click sorts ascending) and then sort the second column, sorting is done after the second column. But if I want to sort again after the first column, I have to unsort the second column so that the sorting after the first column is correct, otherwise it gives us incorrect values.
