### ISSUE TITLE
filtering null values with select type doesn't work

### ISSUE THREAD

**Issue by goldylucks** [inovua/reactdatagrid#19]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

What you did:
I have a column with values either true, false, or null. I have a filter on that column for each one of the values. I select "null" ("Blank" in the UI of the sandbox)

![image](https://user-images.githubusercontent.com/6963212/104211783-2ecf2e00-543d-11eb-8221-d4b7357b7b8a.png)

What happened:
Nothing. I expect to see only the row with the null value, and the word "Blank" in the filter.

Reproduction repository:
https://codesandbox.io/s/small-wood-ldn2d?file=/src/App.js

Problem description:
the filtering doesn't work.

Suggested solution:
do a check for null value in the filter

**Comment by inovua-admin** [comment]
Version `4.0.18` solves this issue
```js
const defaultFilterValue = [
  {
    name: 'enlisted',
    operator: 'eq',
    type: 'select',
    value: null,
    emptyValue: null,
  },
];
```
you have to specify which value is considered the `emptyValue` for the respective filter. Empty values are needed because generally you need a way to clear the filters - when a value from the select box is selected, if it's equal (`===`) to the empty value, the filter is basically cleared.
However, in your example you can now specify `emptyValue` as `undefined`, which will not match any of the values in your select, thus making `null` a valid filter value, which will apply the filter as you expect.

Additionally, if you want to make this the default behaviour for all `select` filters, you need to do the following:

```js
import filterTypes from '@inovua/reactdatagrid-community/filterTypes';

filterTypes.select.emptyValue = undefined; // the default is `null`
```
