### ISSUE TITLE
group columns with undefined values are broken

### ISSUE THREAD

**Issue by goldylucks** [inovua/reactdatagrid#20]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

What you did:
grid with grouping in which some of the cell values are undefined

What happened:
the grouping breaks:
![image](https://user-images.githubusercontent.com/6963212/104213278-c719e280-543e-11eb-9ed6-38a7ea2c6b11.png)

Reproduction repository:
https://codesandbox.io/s/eager-lichterman-ug7k8?file=/src/App.js

Problem description:
Grouping is broken, and some of the data in our grids is undefined.

Suggested solution:
treat undefined like any other value. there should be a group of all undefined data. i.e. in the sandbox above, there would be a second group after "usa", and that group would have one member, with the undefined country and age.

**Comment by inovua-admin** [comment]
`null` and `undefined ` are special since stringifying them ends up with the same value as stringifying  empty strings.
Grouping is implemented via stringification, and a group key needs to be unique for a certain value.
So instead of poluting our codebase with all kind of weird checks, we have exposed [column.groupToString](https://reactdatagrid.io/docs/api-reference#props-columns-groupToString) and  [column.renderGroupTitle](https://reactdatagrid.io/docs/api-reference#props-columns-renderGroupTitle) - you should use those to customize grouping to fit you specific needs - below you can find an example

```js

const groupToString = value =>
  value === null
    ? '<null>'
    : value === undefined
    ? '<undefined>'
    : value || '<empty>';

const renderGroupTitle = value => {
  if (value === '<null>') {
    return 'NULL or whatever group title you need';
  }
  if (value === '<undefined>') {
    return 'UNDEFINED';
  }
  if (value === '<empty>') {
    return 'EMPTY';
  }
  return value;
};
const columns: TypeColumn[] = [
  {
    name: 'country',
    defaultFlex: 1,
    header: 'Country',

    groupToString,
    renderGroupTitle,
  },
  { name: 'firstName', defaultFlex: 1, header: 'First Name' },
  {
    name: 'age',
    type: 'number',
    defaultFlex: 1,
    header: 'Age',
    groupToString,
    renderGroupTitle,
  },
];
```

Let us know how it goes - should do the trick for even the most advanced use-cases.

**Comment by goldylucks** [comment]
The problem is not the display of the group string, the problem is the grouping is broken. It's not grouping correctly. ook at this screenshot for example (from the repro):

![image](https://user-images.githubusercontent.com/6963212/104478637-37ee0580-55cb-11eb-9ae5-77a8084f20d8.png)

You can see that the group "usa" is collapsed, and yet there's an open subgroup beneath it. Isn't this a bug?

**Comment by inovua-admin** [comment]
It is a bug for null and undefined values, but using the `groupToString`/`renderGroupTitle` pair of properties you can workaround those edge cases.

**Comment by goldylucks** [comment]
that did the trick, thanks :)
