### ISSUE TITLE
Grid dynamic height

### ISSUE THREAD

**Issue by AndreeaStirbu** [inovua/reactdatagrid#211]
Is it possible to make the grid body (the rows) have dynamic height based on how many rows I am loading? 
Thank you! :)

**Comment by marcselman** [comment]
I agree, then we could show the grid 'inline'.
If the grid shows pages of 10 items that should be the height and the page footer could be shown below.
Then if the user changes to show 25 items for example, then that would be the height and the page footer will still be below it.

How it works now is that if you show more items the grid will be scrollable.
That's unwanted in our case.

**Comment by inovua-admin** [comment]
Even though this functionality is not implemented by default, you can easily achieve it by using `rowHeight` (default 40), `minHeight`.

**Comment by AndreeaStirbu** [comment]
@inovua-admin Let's say that I set the minHeight to 550px. If I only display 2 rows I would like the grid to shrink and have a smaller height than the minHeight. Is this possible with any component config or css?
![image](https://user-images.githubusercontent.com/33423894/153391153-9f7e8be1-f8a5-4127-a6dd-50268389a51b.png)

I don't want all the white space.

Thanks :)

**Comment by marcselman** [comment]
> Even though this functionality is not implemented by default, you can easily achieve it by using `rowHeight` (default 40), `minHeight`.

It's definitely not that simple. If I just give a minHeight of 40 (rowHeight) * 50 (rowCount) = 2000 the scrollbar still appears.
I need to give a minHeight of 2125 to no longer have a scrollbar visible. So 125 pixels extra. This is probably because of the size of the header rows and the paging row.
But then I still end up with a small bit of space between the rows and the paging row:
![image](https://user-images.githubusercontent.com/514683/155492875-5e6fe741-2554-4985-9b1c-2fd35ab63080.png)

I would have to add some custom CSS to hide that. Then if I want to show/hide some components of the grid I'd have to dynamically calculate the minHeight as well. Basically for every variable that can change the grid height we'd have to calculate the minHeight: changing results per page, themes, header/footer visibility toggles etc... It's doable but feels more like a hack.
It would be a lot easier if the library would just offer a setting where the rows are rendered inline instead of in a scrollable container.

What do you think @inovua-admin?

**Comment by AndreeaStirbu** [comment]
@marcselman said it better, the main issue that I am experiencing is having a different number of records per page. I guess calculating the minHeight dynamically every time I change the page is an option, but definitely not a nice one. It would be amazing if there's anything that could make this computation easier.

**Comment by mednche** [comment]
I'd also love the feature suggested @marcselman. I would like to hide completely the table's scrollbar so that the user can scroll the page (and the table) in a smooth manner.

I also have the same issue as @AndreeaStirbu whereby small tables don't look nice when the table's minHeight is large.

**Comment by marcselman** [comment]
@inovua-admin Could you give us an update on this issue? Is this something that might, or will be implemented? Or should I just create a new issue item since this one was closed by you?

**Comment by marcselman** [comment]
@inovua-admin Can this issue be reopened? As I've shown above it's very hard to build a grid with dynamic height. Support from the library would be extremely helpful.

**Comment by faisalch10** [comment]
@marcselman can you find the fix? I am also facing this issue

**Comment by nurhanna** [comment]
facing same issue here where when the data return is small e.g less than 20 records, there will be huge white gap in between the last row and the footer

**Comment by faisalch10** [comment]
`import ReactDataGrid from '@inovua/reactdatagrid-community';
import PropTypes from 'prop-types';
import '@inovua/reactdatagrid-community/index.css';

const Table = ({ columns, state, setHandleOnTable, currentCount }) => {
  const tableStyles = {
    minHeight: !currentCount ? '300px' : 40 * currentCount + 85 + 'px',
    borderRadius: 5,
    overFlow: 'hidden',
  };

  return (
    <ReactDataGrid
      showColumnMenuTool={false}
      idProperty='_id'
      columns={columns}
      pagination
      dataSource={state.dataSource}
      style={tableStyles}
      defaultLimit={5}
      showActiveRowIndicator={false}
      resizable={false}
      onReady={setHandleOnTable}
    />
  );
};

Table.propTypes = {
  columns: PropTypes.array.isRequired,
  state: PropTypes.object.isRequired,
  setHandleOnTable: PropTypes.func.isRequired,
  currentCount: PropTypes.number.isRequired,
};

export default Table;`

**Comment by faisalch10** [comment]
![image](https://github.com/inovua/reactdatagrid/assets/57663488/1eb3399e-af62-40c1-945f-4f8d7d0a99e0)
@nurhanna Check this. I am able to fixed it
