### ISSUE TITLE
buggy gridRef.visibleColumns

### ISSUE THREAD

**Issue by goldylucks** [inovua/reactdatagrid#22]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

What you did: printed `gridRef?.current.visibleColumns.length` when there were 5 columns

What happened: resulted to 4

![image](https://user-images.githubusercontent.com/6963212/104915873-ef9f6080-5999-11eb-938d-a7b3909f65c6.png)

Reproduction repository:
https://codesandbox.io/s/vibrant-grass-0wvbe?file=/src/App.js:1183-1221

Problem description:
there are two bugs here. the initial column length is 4. when I clear both groupings, it goes to 5, which is correct. Afterwards, if I group by two groupings, and then cancel one, it goes back to 4.

**Comment by inovua-admin** [comment]
You're not using the api in a correct way - your render is 1 frame/render behind
Basically, when groupBy is changed - so your setGroupBy is called, the visibleColumns is not yet updated - it will update on the next render, but you're rending the old value. You should only use the api for imperative stuff that you can't otherwise perform via props (controlled or uncontrolled).
To prove it, you can set the `ref` (the `ref`, not `ref.current`) as a global variable, and can put it in the devtools live expression watch to see it's updated correctly

**Comment by goldylucks** [comment]
thanks for the prompt response.

The visible columns shouldn't change when grouping is changed tho.

**Comment by goldylucks** [comment]
thanks for the prompt response.

The visible columns shouldn't change when grouping is changed tho.

**Comment by inovua-admin** [comment]
visible columns refers to what is currently visible in the grid - so if you have groupColumn: true, then a new column is generated and added for the group, thus it appears in visibleColumns.
