### ISSUE TITLE
Grid cells lost position on paging back from the last page and end of the scroll

### ISSUE THREAD

**Issue by SunilHirol** [inovua/reactdatagrid#58]
There is an issue when the table has greater than 14 columns and If scrolling all the way to the left (end of table/last column) and also paging to the last page.
If the last page has less than rows of default limit rows and then paging back the table cells lost their position and the position is back only when scrolling a side. 

I have checked into the developer tools those cells style left property is set to 0.

Please look into the attachments
![paging back](https://user-images.githubusercontent.com/69301294/109486046-63a84a80-7aa8-11eb-879c-b9b00014a505.png)

**Comment by inovua-admin** [comment]
Thanks for the report. would help if we can have a codesandbox with a repro of this. Seems like a similar issue has been reported at #28 and the solution for now is the same, just specify `virtualizeColumns=false` (see https://reactdatagrid.io/docs/api-reference#props-virtualizeColumns)

It's because by default, starting at 14, which is the [virtualizeColumnsThreshold]( https://reactdatagrid.io/docs/api-reference#props-virtualizeColumnsThreshold), columns are being virtualized, but seems like we have a bug in horizontal virtualization, which we're working on to come up with a fix.

**Comment by SunilHirol** [comment]
Thanks, resolved my problem using `virtualizeColumns=false`

**Comment by inovua-admin** [comment]
Fixed in `4.0.34`
